[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[phases.build.env]
DATABASE_URL = "postgresql://placeholder:placeholder@placeholder/placeholder"

[start]
cmd = "npm start"
